#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

environment:
  matrix:
  - config: Dev
  - config: RelWithDebInfo

# branches to build
branches:
  # whitelist
  only:
    - master

shallow_clone: true

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\osmium-tool

platform: x64

install_script:
  - scripts\build-appveyor.bat

build: off
test: off
deploy: off
