name: Install on Windows

runs:
  using: composite
  steps:
    - name: Install packages
      run: vcpkg install expat:x64-windows bzip2:x64-windows lz4:x64-windows zlib:x64-windows boost-crc:x64-windows boost-iterator:x64-windows boost-program-options:x64-windows boost-variant:x64-windows
      shell: bash
    - name: Install from git
      run: |
        git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
        git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
      shell: bash

